---
title: "descriptivos"
author: "equipo EDUMER"
date: "2022-12-19"
output: html_document
---

# Cargar paquetes

```{r}
pacman::p_load(dplyr, haven, stargazer, sjmisc, sjPlot, tidyverse)
```

# cargar base de datos desiguales 2016 (del PNUD)

```{r}
data <- read_dta("input/original/desiguales2016.dta")

summary(data$p12_sal_real_cajero_m)
```

# salario real (promedio de percepción cuánto ganan en cada oficio diferenciado por sexo, según sexo)

```{r}
salario_real = data %>% group_by(sexo) %>%
  summarise(n = n(),
            cajero_hombre = round(mean(p12_sal_real_cajero_h, na.rm = T)),
            cajero_mujer = round(mean(p12_sal_real_cajero_m, na.rm = T)),
            gerente_hombre = round(mean(p12_sal_real_gerente_h, na.rm = T)),
            gerente_mujer = round(mean(p12_sal_real_gerente_m, na.rm = T)),
            doctor_hombre = round(mean(p12_sal_real_doctor_h, na.rm = T)),
            doctor_mujer = round(mean(p12_sal_real_doctor_m, na.rm = T)),
            diputado_hombre = round(mean(p12_sal_real_diput_h, na.rm = T)),
            diputado_mujer = round(mean(p12_sal_real_diput_m, na.rm = T))
            )
```


```{r}
salario_real_long <- salario_real %>% 
  pivot_longer(cols = c("cajero_hombre", 
                        "cajero_mujer", 
                        "gerente_hombre", 
                        "gerente_mujer", 
                        "doctor_hombre", 
                        "doctor_mujer", 
                        "diputado_hombre", 
                        "diputado_mujer"), 
               names_to = "oficio",
               values_to = "mean")

salario_real_long$sexo <- as_factor(salario_real_long$sexo)
```

# Gráfico diferencias de promedio

```{r}
dif_salarios <- ggplot(salario_real_long, aes(x = oficio, y = mean, color=sexo)) +
  geom_point(size=4, aes(shape=sexo)) +
  labs(color = "Sexo", shape="Sexo") +
  xlab("Oficio") + ylab("Salario percibido")  +
  theme_bw() +
  geom_text(aes(y = mean, label = mean), 
            position = position_dodge(width = 0.9), size=3, vjust=-1, hjust=0.5 ,col="black") +
  theme(axis.text = element_text(angle = 45, hjust = 1))

dif_salarios

ggsave(dif_salarios, file = "output/graphs/dif_salarios.png")
```


